apps/logs/urls.py
from django.conf.urls import url, include
from .views import (
	LogSearchView
	)

urlpatterns = [
	url(r'^search/$', LogSearchView.as_view(), name="log-search"),
	url(r'^search-box/$', LogSearchView.as_view(), name="log-search-box")
]

detexian/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token
from allauth.account.views import password_change
from dashboard.views import DashboardView


urlpatterns = [
    # Examples:
    # url(r'^$', 'detexian.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', DashboardView.as_view(), name="index"),
    url(r'^alerts/', include('alerts.urls')),
    url(r'^logs/', include('logs.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', TemplateView.as_view(template_name='account/profile.html'), name="profile"),
    url(r"^accounts/settings/$", password_change,
        name="account_change_password"),
    url(r'^api/host/', include('hosts.api.urls')),
    url(r'^api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/alerts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.conf import settings

from .search import AlertIndex, EventIndex

from functools import partial
from datetime import datetime


class Alert(models.Model):

	ALERT_STATUS = (
		("Unreviewed", "Unreviewed"),
		("Researching", "Researching"),
		("In Progress", "In Progress"),
		("Resolved", "Resolved"),
	)

	ALERT_SEVERITY = (
		("Low", "LOW"),
		("Medium", "MEDIUM"),
		("High", "HIGH"),
		("Critical", "CRITICAL"),
	)


	client_id = models.CharField(max_length=100, null=True, blank=True)
	name = models.CharField(max_length=100, null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, null=True)
	event = models.ManyToManyField("Event", blank=True)
	reviewer = models.CharField(max_length=100, null=True, blank=True)
	review_time = models.DateTimeField(null=True, blank=True)
	status = models.CharField(max_length=20, choices=ALERT_STATUS, default="Unreviewed")
	severity = models.CharField(max_length=10, choices=ALERT_SEVERITY, default="Low")

	def __str__(self):
		return self.name

	class Meta:
		ordering = ('-created_at',)
		db_table = 'Alert'

	def alert_server(self):
		return self.client_id.split('-')[0]

	def alert_user(self):
		return self.client_id.split('-')[1]

	# Add indexing method to Alert
	def indexing(self):
		obj = AlertIndex(
		meta={'id': self.id},
		server_ip=self.client_id.split('-')[0],
		name=self.name,
		logged_user=self.client_id.split('-')[1],
		created_at=datetime.strftime(self.created_at, "%d %B %Y %H:%M %p"),
		status=self.status
		)
		obj.save()
		return obj.to_dict(include_meta=True)


class Event(models.Model):

	name = models.CharField(max_length=100, null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, null=True)

	# Add indexing method to Alert
	def indexing(self):
		obj = EventIndex(
		meta={'id': self.id},
		name=self.name,
		created_at=datetime.strftime(self.created_at, "%d %B %Y %H:%M %p"),
		)
		obj.save()
		return obj.to_dict(include_meta=True)

apps/logs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.http import JsonResponse, HttpResponse

from alerts.forms import SearchForm
from alerts.search import event_search

class LogSearchView(FormView):
	form_class = SearchForm
	success_url = "/logs/search/"
	template_name = "logs/search.html"
	data = {}

	def post(self, request, **kwargs):
		search_text = self.request.POST.get("search_text")
		if self.request.POST and self.request.is_ajax():
			data = {}
			data["log_list"] = event_search(str(search_text))
    		return JsonResponse(data)

		return super(LogSearchView, self).post(request, **kwargs)

templates/logs/search-box.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Log Search Box" %}{% endblock %}
{% block head %}
  <style>
    .hidden{
      display: none;
    }
  </style>
{% endblock %}
{% block content %}

  <div id="header_wrapper" class="header-sm">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <header id="header">
            <h1>{% trans "SEARCH LOGS BOX" %}</h1>
          </header>
        </div>
      </div>
    </div>
  </div>

  <div id="content" class="container-fluid">
    <div class="content-body">
      <div id="dashboard_content" class="tab-content">
        <div class="tab-pane fade active in" id="dashboard1">
          <div class="row">
            <div class="col-xs-12 col-sm-12 search-table">
                <form method="post" action="" id="search_form">{% csrf_token %}
                  <input id="id_name" name="search_text" type="text" maxlength="50"></td>
                  <button type="submit" value="Search">Search</button>
                </form>
                <div class="card log-card hidden">
                  <div class="card-heading"><strong>Search Results</strong></div>
                  <div class="card-body">
                   <div class="table-responsive">
                        <table class="table table-striped">
                          <thead>
                            <tr>
                                <th> Name </th>
                                <th> Date </th>
                            </tr>
                          </thead>
                          <tbody class="table-body">
                          </tbody>
                        </table>
                      </div>
                  </div>
                </div>

                <div class="card no-log-card hidden">
                  <div class="card-heading"><strong>No Search Results Found !</strong></div>
                </div>

            </div>
          </div>
        </div>
      </div>
      <!-- ENDS $dashboard_content -->
    </div>
  </div>
  <!-- ENDS $content -->
{% endblock %}

{% block js %}
  <script>
    $(document).ready(function(){
      $("#search_form").on("submit", function() {
          input = $("#id_name").val();
          data = "text=" + input;
          $.ajax({
            url: '/logs/search/',
            type: 'POST',
            data: {
              'search_text': input,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
              var search_hits = data["log_list"]["hits"]["hits"];
              var log_div = $('.table-body');
              if (search_hits.length === 0){
                $(".log-card").addClass("hidden");
                $(".no-log-card").removeClass("hidden");
                log_div.html('');
              }
              else{
                $(".log-card").removeClass("hidden");
                $(".no-log-card").addClass("hidden");
                log_div.html('');
                $.each(search_hits, function(key,valueObj){
                    log_div.append('<tr><td>'+valueObj._source.name+'</td><td>'+valueObj._source.created_at+'</td></tr>');
                });
              }
              console.log("Search Form submitted Successfully");
            },
            error : function() {
              console.log("Error submitting search form");
            }

          });
          return false;
        });
    });
  </script>
{% endblock %}

templates/logs/search.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Log Search" %}{% endblock %}
{% block head %}
  <style>
    .hidden{
      display: none;
    }
  </style>
{% endblock %}
{% block content %}

  <div id="header_wrapper" class="header-sm">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <header id="header">
            <h1>{% trans "SEARCH LOGS" %}</h1>
          </header>
        </div>
      </div>
    </div>
  </div>

  <div id="content" class="container-fluid">
    <div class="content-body">
      <div id="dashboard_content" class="tab-content">
        <div class="tab-pane fade active in" id="dashboard1">
          <div class="row">
            <div class="col-xs-12 col-sm-12 search-table">
                <form method="post" action="" id="search_form">{% csrf_token %}
                  <input id="id_name" name="search_text" type="text" maxlength="50"></td>
                  <button type="submit" value="Search">Search</button>
                </form>
                <div class="card log-card hidden">
                  <div class="card-heading"><strong>Search Results</strong></div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped">
                        <thead>
                          <tr>
                              <th> Name </th>
                              <th> Date </th>
                          </tr>
                        </thead>
                        <tbody class="table-body">
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>

                <div class="card no-log-card hidden">
                  <div class="card-heading"><strong>No Search Results Found !</strong></div>
                </div>

            </div>
          </div>
        </div>
      </div>
      <!-- ENDS $dashboard_content -->
    </div>
  </div>
  <!-- ENDS $content -->
{% endblock %}

{% block js %}
  <script>
    $(document).ready(function(){
      $("#search_form").on("submit", function() {
          input = $("#id_name").val();
          data = "text=" + input;
          $.ajax({
            url: '/logs/search/',
            type: 'POST',
            data: {
              'search_text': input,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
              var search_hits = data["log_list"]["hits"]["hits"];
              var log_div = $('.table-body');
              if (search_hits.length === 0){
                $(".log-card").addClass("hidden");
                $(".no-log-card").removeClass("hidden");
                log_div.html('');
              }
              else{
                $(".log-card").removeClass("hidden");
                $(".no-log-card").addClass("hidden");
                log_div.html('');
                $.each(search_hits, function(key,valueObj){
                    log_div.append('<tr><td>'+valueObj._source.name+'</td><td>'+valueObj._source.created_at+'</td></tr>');
                });
              }
              console.log("Search Form submitted Successfully");
            },
            error : function() {
              console.log("Error submitting search form");
            }

          });
          return false;
        });
    });
  </script>
{% endblock %}